version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
    mysql:
      driver: ${VOLUMES_DRIVER}

services:

### Workspace Utilities ##################################
    scrapy:
        build:
            context: ./scrapy
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        networks:
            - frontend
            - backend
